KEY_ACTION_LIST = "KEY_ACTION_LIST"

ACTION_SIGN = 1
ACTION_LOGIN = 2
ACTION_PLAY = 3

KEY_ACTION_TASK_LIST = "KEY_ACTION_TASK_LIST"
KEY_ACTION_ACTIVE_LIST = "KEY_ACTION_ACTIVE_LIST"

ACTION_MAPPING = {
    ACTION_SIGN:[KEY_ACTION_TASK_LIST,KEY_ACTION_ACTIVE_LIST],
    ACTION_PLAY:[KEY_ACTION_TASK_LIST]
}
